//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam032
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class netEntities1 : DbContext
    {
        public netEntities1()
            : base("name=netEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<gys> gys { get; set; }
        public virtual DbSet<list> list { get; set; }
        public virtual DbSet<sp> sp { get; set; }
        public virtual DbSet<zl> zl { get; set; }
    }
}
