//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam032
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp
    {
        public string spid { get; set; }
        public string spname { get; set; }
        public string spzlid { get; set; }
        public string spgysid { get; set; }
    
        public virtual gys gys { get; set; }
        public virtual zl zl { get; set; }
    }
}
